name: Deploy and test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Install Packages
        run: npm ci
      - name: Run Test
        run: npm run test
